### ISSUE TITLE
Modification of the opening of the sub-menu - on hover

### ISSUE THREAD

**Issue by julienstuder** [CodyHouse/cd-mega-site-navigation-changelog#1]
How can i change opening of the sub-menu on hover instead of on click ?

**Comment by julienstuder** [comment]
in _3_mega-site-navigation.js  i changed lines 151 and 210 : click ==> mouseover.
it works partially. When over the arrow icon the submenu appears/desappears in a very flashy way :)

**Comment by claudia-romano** [comment]
Hi there, adding a pointer-events: none to the arrow icon element should fix your issue.

**Comment by julienstuder** [comment]
Thanks Claudia that did the trick !

**Comment by dean-shanghai** [comment]
@claudia-romano @sebastiano-guerriero This is buggy, can you kindly provide a clean mouseover/mouseleave version?

**Comment by claudia-romano** [comment]
Hi Dean, we have added a new `data-hover` option to open the subnavigation elements on hover. More info here:
https://codyhouse.co/ds/components/info/mega-site-navigation#open-on-hover

You can get the updated code here:
https://codyhouse.co/ds/components/app/mega-site-navigation

Cheers

**Comment by dean-shanghai** [comment]
Nice job!
