### ISSUE TITLE
CLS mitigation

### ISSUE THREAD

**Issue by radum** [CodyHouse/cd-mega-site-navigation-changelog#10]
Hello,

Have you ever experienced a problem on how the MegaNav was built to work and core web vitals CLS metric?

In my own usage on a large scale application the fact that the meganav starts in mobile mode and then the JS kicks in to transition it to desktop mode based on the added css class triggers a CLS of at least 0.23.

Not sure what would be the best way to fix this apart from changing the way it works completely.

**Comment by claudia-romano** [comment]
Hi there, I see your point. 
On a large scale application, you may need to separate the JS of the mega navigation from the rest of your JS and make sure it is loaded first so that you can reduce the layout shift. Is this something you could try? 

Cheers!

**Comment by radum** [comment]
Hey, that was the first thing I did, and on a very simple page it works fine, but the moment we start expanding that with more stuff and with 3rd party scripts also, it always fires. And its on an average of 0.25 CLS. The only I managed to fix it is to remove the JS dependency and do it all from css. It removes some of the features you get out of the box but it is the only solution I can think off.

**Comment by claudia-romano** [comment]
Hi there, thanks for the feedback. We'll look more into it! 
May I ask if you kept including the mega nav js before those 3rd party scripts? Even if additional scripts are used, the mega nav js should not be affected if included first. Thank you!

**Comment by radum** [comment]
Yes I did. I did lots of tests and on very simple pages the shift is so fast is not caught by CLS, but the moment the page gets more complicated with images and so on it will be flagged as a CLS even if its almost invisible to the human eye.

It gets worse on slow network speeds.

Reading the code I understand the reasons behind your choice, but I think there are other ways to fix this in pure CSS and so removing the JS dependency.

**Comment by claudia-romano** [comment]
I see, thanks for the feedback. 

With complex layout like the one of the mega site nav, a pure CSS solution becomes quite complex to maintain; the JS dependency allows to handle two different styles using two classes with no need to overwrite CSS. 

The alternative (CSS only) approach would be to duplicate the HTML code and  show only one of the two versions based on the breakpoint (not the best option either).

In you case, you could use a script in the ```<head>```  that adds a specific class to the ```<html>``` based on the viewport size. Then you could apply different style based on that custom class. That would remove the CLS.

**Comment by radum** [comment]
I ended up changing the html a bit and moving the desktop and mobile CSS under media queries. It solved the problem completely.

In my case it's a better solution than render block the head, even if it is just for a short period.

Thanks for your help.
