### ISSUE TITLE
Unable to run yarn build - SCSS file compilation error on Nuxt 2

### ISSUE THREAD

**Issue by gkurl** [CodyHouse/cd-mega-site-navigation-changelog#11]
Hello CodyHouse team,

Repo for this issue: [here](https://gitlab.com/gkurl/vapedcrusader)

I am unable to run `yarn build` with this on the latest Nuxt 2 (2.15.8)

I have been singling out what may be potentially causing the below Nuxt compilation error seen here:

```
ERROR in ./components/AppNavigation.vue?vue&type=style&index=0&id=c8f09730&prod&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./components/AppNavigation.vue?vue&type=style&index=0&id=c8f09730&prod&lang=scss&)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
ParserError: Syntax Error at line: 1, column 23
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/components/AppNavigation.vue:1:198660
    at Parser.error (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:127:11)
    at Parser.operator (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:162:20)
    at Parser.parseTokens (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:245:14)
    at Parser.loop (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-custom-properties/index.cjs.js:333:24
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:194:18
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:139:18
    at Rule.each (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:105:16)
    at Rule.walk (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:135:17)
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:152:24
    at Root.each (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:105:16)
    at Root.walk (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:135:17)
    at Root.walkDecls (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss/lib/container.js:192:19)
    at transformProperties (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-custom-properties/index.cjs.js:330:8)
    at Object.syncTransform [as plugin] (/Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-custom-properties/index.cjs.js:522:5)
    at /Users/gkurl/Documents/vapedcrusader-frontend/vapedcrusader/node_modules/postcss-preset-env/index.js:459:97
 @ ./components/AppNavigation.vue?vue&type=style&index=0&id=c8f09730&prod&lang=scss& (./node_modules/vue-style-loader??ref--7-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-1-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-1-3!./node_modules/@nuxt/components/dist/loader.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./components/AppNavigation.vue?vue&type=style&index=0&id=c8f09730&prod&lang=scss&) 4:14-450
 @ ./components/AppNavigation.vue?vue&type=style&index=0&id=c8f09730&prod&lang=scss&
 @ ./components/AppNavigation.vue
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./node_modules/@nuxt/components/lib/installComponents.js ./.nuxt/client.js

 FATAL  Nuxt build error                                              18:33:27

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:2127:21)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:2076:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:327:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:110:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:413:7)
```

I am able to run `yarn run dev` but above issue occurs when attempting to build.

I did some investigation my side into the component seen in the error message.

So my `AppNavigation.vue` is using just the mega-site navigation + all it's dependencies - I tried commenting out each `.scss` file in the mega-nav scss file and I managed to run `yarn build` by specifically excluding `_2_dropdown.scss` file:

Video demonstrating the issue:

https://user-images.githubusercontent.com/34505859/208742871-d8958760-51de-4f75-a5b6-824d2fec04df.mp4

I'm not sure what the issue might be here - hoping you can help me deduce what is required? Maybe the file is using some incompatible sass methods or similar, maybe additional npm packages are required etc? Appreciate your insight on this.

I am definitely using the correct versions of `sass` and `sass-loader@10` and it is building once you comment out that dropdown scss file. 

@claudia-romano 

Thanks

**Comment by claudia-romano** [comment]
Hi there,
the dropdown component uses the `spaceUnit` and `textUnit` mixins. Could you try commenting them out and see if this fixes the issue? Thanks.

**Comment by gkurl** [comment]
> `spaceUnit`

Hi Claudia thanksn for replying - forgot to mention in my original post I had tried this. Just tried again:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/34505859/209141271-777ce14b-db8c-4c1c-8241-bbca2334d835.png">

Still get the nuxt build error however.

**Comment by claudia-romano** [comment]
ok thanks for trying that. Have you tried using the CSS version of the dropdown component (rather than the SCSS version). This way we can make sure this is actually a SASS compiling issue. Thanks

**Comment by gkurl** [comment]
Hi just getting over the holiday season, hope you had a good new year. I will try switching out to CSS and let you knows, quick post from me to let you know I'm still active.

**Comment by gkurl** [comment]
Hello - I have tried replacing the scss code in the dropdown scss file with CSS from the component page and still get the same compilation error.

**Comment by claudia-romano** [comment]
Thanks for trying that. 
If you are still getting the same error, then it cannot be a SCSS to CSS compilation error. Try leaving the file empty and see if you still have the issue. If this is the case, then make sure you are properly importing that file (e.g., wrong path or file name).

**Comment by gkurl** [comment]
I've double checked the import - the file is definitely being imported correctly - because I am importing base and tabs.scss the same way and they seem fine. If I comment out the contents, but leave the file imported, it compiles fine. 

The only two scenarios it compiles in are - either leaving the dropdown.scss file out all-together/commenting it out, or leaving the file imported, but commenting out it's contents.

**Comment by gkurl** [comment]
I've been commenting out bracket by bracket the css version and running build each time to try and figure out - it seems I've narrowed it down to css/scss that includes calc like this:

```
.dropdown__sub-wrapper .dropdown__menu {
  top: calc(var(--space-xxs) * -1);
}

```

```
.dropdown__sub-wrapper > .dropdown__menu {
  top: calc(var(--space-xxs) * -1);
  box-shadow: var(--inner-glow), var(--shadow-md);
}
```

If I comment these out, it builds/compiles fine, is it potentially an issue with the formula? `* -1`? I'm not a css expert so not sure how calc works. 

This calc seems to work fine when included and I noticed it's using a positive number:

```
.dropdown__sub-wrapper > .dropdown__item {
  position: relative;
  padding-right: calc(var(--space-sm) + 12px);
}
```

**Comment by claudia-romano** [comment]
Thanks for the additional info. That looks more like an issue with Nuxt (and the postcss plugin it uses by default). Please take a look at this other similar issue:
https://github.com/nuxt-modules/tailwindcss/issues/350#issuecomment-846714759

**Comment by gkurl** [comment]
Thanks for the link. Useful to know but I am not using tailwind, just pure scss and html in this instance and tried the post-css import as mentioned in that thread so am still stuck so not sure how to proceed from here. Hoping Nuxt 3 does not have similar issues for future projects.

**Comment by claudia-romano** [comment]
I see. Did you try the cssnano config option in addition to the postcss-import?
Meanwhile, you could also try inverting the two elements in the calc:
```
top: calc(-1 * var(--space-xxs));
```
or also try with parentheses:
```
top: calc((-1) * var(--space-xxs));
```

**Comment by claudia-romano** [comment]
I'm closing this as no additional info was provided. Feel free to reopen it if you are still experiencing the same bug. Cheers!
