### ISSUE TITLE
IE11 support ?

### ISSUE THREAD

**Issue by julienstuder** [CodyHouse/cd-mega-site-navigation-changelog#3]
i see that the gallery submenu is broken under ie11.
is there a fix ?

**Comment by claudia-romano** [comment]
The gallery submenu uses CSS Grid which is not supported in IE11. If you want to add a fallback, modify the scss code of the ```.mega-nav__sub-nav--layout-3``` using the ```gridFallback``` mixin:
```
.mega-nav__sub-nav--layout-3 { // layout 3 -> gallery
    @include gridFallback(var(--space-md));
    margin-left: auto;
    margin-right: auto;
    @supports (grid-area: auto) {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: var(--space-md);
      margin: 0 auto;
    }

    > * {
      @include column(1/4);
    }
  }
```
Make sure you are targetting the desktop version of the menu in the scss file. You can find more info about the ```gridFallback``` mixin on our doc page:
https://codyhouse.co/ds/docs/framework/grid-layout#grid-system

**Comment by claudia-romano** [comment]
Hi there, 
we have pushed a new version of the mega site nav with the CSS code (commented) that you can use to support IE11 (```.mega-nav__sub-nav--layout-2``` and ```.mega-nav__sub-nav--layout-3``` classes). You can check the updated code on the component demo page:
https://codyhouse.co/ds/components/app/mega-site-navigation

Feel free to reopen this issue if you are still having problems. Cheers!
