### ISSUE TITLE
Keyboard control for mega-nav__sub-nav--layout-1

### ISSUE THREAD

**Issue by dsite** [CodyHouse/cd-mega-site-navigation-changelog#4]
I've been grateful at how accessible you've made your components, particularly the megamenu. Not a lot of frameworks and templates do that well. 

As I've been testing the keyboard navigation, there are two parts that seem counterintuitive:

### Arrow navigation inside Menu Layout 1
First, in the desktop version of menu layout 1, once I tab into the menu, I would expect to be able to use the up and down arrows to navigate the vertical menu option tabs (Product One, Product Two, Product Three). Instead, I need to use the left and right arrows. I understand that you are using the tabs component and that this is the standard keyboard navigation for horizontal tabs. But it seems to go against convention in the case of vertical tabs.

From [WAI](https://www.w3.org/TR/wai-aria-practices-1.1/#tabpanel):

> If the tabs in a tab list are arranged vertically:
> 1. `Down Arrow` performs as `Right Arrow` is described above.
> 2. `Up Arrow` performs as `Left Arrow` is described above.

### Tab behavior inside Menu Layout 1
Second, also in the desktop version of menu layout 1, I tab into the Products menu and get focus on Product One. Then I tab through the links in the Product One section (image > Learn More > Buy). The next tab closes the menu and puts the focus on the next main menu item (Lists). That jump seems counterintuitive to me. It would be more intuitive to me for the tab key to take me from the Product One Buy button to Product Two. Instead, I have to shift-tab three times and then press the right arrow.

I don't know the right answer here. I'm admittedly not someone who relies on keyboard navigation. And I am definitely someone who is still learning about accessibility best practices. So maybe this is the proper action and is what someone who relies on keyboard navigation would expect. It's hard to tell from the WAI documentation what is the right approach. I just thought I'd mention it, as long as I was addressing the previous issue.

Thanks for all of the work that you've put into this framework. I'm having fun exploring the components.

**Comment by claudia-romano** [comment]
Hi there,
thanks for the suggestions.

**Arrow navigation inside Menu Layout 1**
This is a good point. We have updated the tabs component to include a new attribute that can be set to 'vertical' to change the way the tabs are navigated (with up/down or left/right arrows). You can test the new behaviour here:
https://codyhouse.co/ds/components/app/mega-site-navigation

This still preserves the left/right navigation for horizontal tabs:
https://codyhouse.co/ds/components/app/tabs

**Tab behavior inside Menu Layout 1**
This is a more complex point. Tabs are groups of related content that display one panel of content at a time. This does not force the user to go through the contents of all the tabs but only the content they are actually interested in. The left/right or up/down keys are used to select the panel of interest and the tab is used to navigate the content.

If we were to put the focus on 'Product Two', then we would force the user to go through the entire content of this new tab (the same for all the remaining tabs). As you were saying, the WAI docs does not provide clear details about that.
We won't be changing this behaviour for now so I'll close this issue. But if you find any more material about the issue that suggests a different behaviour, feel free to reopen it. Thanks!

**Comment by dsite** [comment]
Thank you so much for adding that so quickly. That's an excellent solution.

I agree that there isn't a clear cut answer to the second point, and I respect your decision to leave it the way it is.

Have a nice day!

**Comment by dsite** [comment]
Hi again,

As I've worked a bit more with the menu, I have two more observations. One has to do with the solution above and one is related.

### Arrows continue to scroll the page
Now that I've integrated the new attribute and script into my project, I've noticed one behavior that seems suboptimal: when you are in the megamenu and using the up and down arrows to cycle through the vertical tabs, the arrows also continue to scroll the underlying page. It's not immediately evident from the component example because there is not scrollable content on the page.

Would it be better to prevent the default behavior of the arrows while the focus is in the megamenu? 

### Arrow navigation for the other megamenu dropdowns?
I also wonder if it would be more accessible to make the other sub-nav layouts navigable with arrow keys. A decent example of this is the megamenu on the main [Adobe](https://adobe.com) site. They released [an example script](https://adobe-accessibility.github.io/Accessible-Mega-Menu/) and [explained their reasoning](http://blogs.adobe.com/accessibility/2013/05/adobe-com.html) for their interaction design choices.

Again, WAI doesn't say much about megamenus, as they are kind of a weird hybrid between tabs and menus. So if you want to keep the current behavior, I'd understand. I just thought I'd mention it for your consideration.

Thanks again for your time.

**Comment by claudia-romano** [comment]
Hi there, thanks for the heads-up. We have updated the Tabs component to fix the default scrolling on keyboard navigation. You can get the updated code here:
https://codyhouse.co/ds/components/app/tabs

About the second point: thanks for sharing the article. We'll look into it! 

Cheers
