### ISSUE TITLE
Removing Account menu seems to break Safari

### ISSUE THREAD

**Issue by dsite** [CodyHouse/cd-mega-site-navigation-changelog#5]
**Problem:** Removing the Account menu HTML seems to break the menu display on mobile Safari and desktop Safari at narrow breakpoints.

**What it looks like:** The desktop menu shows up instead of the mobile icons (see screenshot below).

**The long version of how I diagnosed the issue:**
I was testing a prototype with the mega site navigation component, and I noticed on my iPhone that the mobile menu was not displaying properly. Instead of the icons, the desktop links showed up.

I'd tested with Chrome and Firefox dev tools and hadn't seen such behavior. But I pulled the site up in Safari, narrowed the browser window, and it was displaying poorly there, too.

I spun up a new testing server and did a fresh install from my CodyHouse framework download. I compiled the stylesheet and javascript and created a simple HTML page with just the copied HTML from the component info page. It worked perfectly. I dropped in the stylesheet from my prototype site. It worked perfectly. So I figured it must be something to do with the HTML from my prototype menu. I replaced the default menu with my menu, and it broke. I cleared the menu and started adding my menu sections from the top down. Everything worked perfectly until I got all the way down to the `icon buttons --desktop` section (line 361).

I had removed the account dropdown from my prototype, because it's not something that I need for the site. And I discovered that removing that is what was breaking things for me in Safari. When it was gone, it was broken. When I put it back in, it was fixed.

I went back to the default component HTML, and the same thing happened when I removed the `div.dropdown`:

![Megamenu Test - Mobile Safari](https://user-images.githubusercontent.com/56164564/93727704-55b1dd80-fb8a-11ea-981f-8b9ee6837256.jpg)

I feel like this is something I should be able to troubleshoot, but I've poked through dev tools and the CSS and I'm still puzzled. I couldn't find it in the JS, but that's admittedly not my strength. I tried removing sub-portions to see if I could narrow it down further, but I could not. (Interestingly, I found that if I add a `display: none` style to the `div.dropdown`, everything continues to work perfectly.)

___

I know that was a lot to read, but I wanted to let you know what I tried, in the hopes that you might be able to duplicate this behavior. If you need any additional information from me about my framework setup or if you need me to set up an example so that you can see it for yourself, please let me know.

Thanks for your time.

**Comment by sebastiano-guerriero** [comment]
Hi there!

I've commented out the account dropdown on line 363, and tested the navigation on Safari 13 and 14 and it seems to be working fine. I've also tested on iOS, and it's working there as well.

<img width="1384" alt="Screenshot 2020-09-21 at 08 31 20" src="https://user-images.githubusercontent.com/5512742/93737972-db627700-fbe4-11ea-9034-8d02f5930577.png">

Is it possible that you haven't removed the wrapper with the .js-dropdown class, but only its content? It appears a JS problem (we use JS to toggle the layout change). If the .js-dropdown class wasn't removed, it would cause a JS issue.

**Comment by dsite** [comment]
Hmmm... I definitely commented out the .js-dropdown div. 

The test that I did included the SCSS and JS for the full set of components in my build. To simplify things, I set up another server, uploaded just the SCSS and JS files necessary for the mega site navigation component, did an `npm install`, did a `gulp watch`, and set up the index.html with just the mega site navigation HTML in the body.

I opened it up in Safari and made the window as narrow as I could. The menu worked perfectly. 

I commented out `div.js-dropdown` and refreshed, and the menu broke. 

I cleared my caches. I made sure that I had no extensions loaded in Safari. I loaded it in an incognito window.

Here is my setup, showing the files I used to build the site and showing which part I commented out:

<img width="819" alt="test-setup" src="https://user-images.githubusercontent.com/56164564/93780958-cc84c000-fbf6-11ea-88ee-afa6ca33eec9.png">

Here is a slightly low-resolution GIF showing the behavior I see:

![issue-example](https://user-images.githubusercontent.com/56164564/93781112-02c23f80-fbf7-11ea-9e77-2499cf39b673.gif)

You can see a similar example in higher resolution here:
https://cln.sh/jqpH2T

If you want to test for yourself, here is my test site:
* [Commented Out](https://meganav.dsite.com)
* [Not Commented Out](https://meganav.dsite.com/fixed.html)

One thing I will note is that any change in browser window size or any scrolling of the window seems to clear up the issue. But it returns on refresh. So if the Commented Out version looks like it is not broken, please try a refresh.

Thank you for looking in to this and for your time.

**Comment by claudia-romano** [comment]
Hi there,
thank you for providing this additional info.
Unfortunately, we were not able to replicate the issue on our side. But we have just pushed an updated version of the component with some changes that may solve the issue you are experiencing. 

You can get the updated JS code here:
https://codyhouse.co/ds/components/app/mega-site-navigation

Please let me know if you are still experiencing the problem. Cheers!

**Comment by dsite** [comment]
Thanks for looking into this, even if you couldn't replicate it. Your updated JS did fix the issue. Hooray!

[Version with new code](https://meganav.dsite.com/newcode.html)

Thanks again for your help and for all of the work that went in to making and improving the framework.
