### ISSUE TITLE
Open nav item on hover

### ISSUE THREAD

**Issue by basderuijter** [CodyHouse/cd-mega-site-navigation-changelog#6]
Hi, is it possible to make the nav__item open on hover instead of on click? Can't seem to find it.. Hope you can help me out!

**Comment by basderuijter** [comment]
I made it work.. It's now opening on hover. But now I wan't to have it close when leaving the mouse from the sub nav, would be great if you can help me

**Comment by claudia-romano** [comment]
Please make sure to check this issue:
https://github.com/CodyHouse/cd-mega-site-navigation-changelog/issues/1

Cheers
