### ISSUE TITLE
Mouse-Over Open

### ISSUE THREAD

**Issue by bacounts** [CodyHouse/cd-mega-site-navigation-changelog#7]
Is it possible to have each "mega-nav__item" open on mouse-over instead of on-click?

I was going to play around with the code, but I am concerned about messing up the accessibility in the JS code.

**Comment by claudia-romano** [comment]
Hi there, please make sure to check this issue:
https://github.com/CodyHouse/cd-mega-site-navigation-changelog/issues/1

Cheers
